openapi: "3.0.1"
info:
  version:  1.0.0 | 20.09.2025
  title: Content Management Service API
  description: API для управления учебными материалами в системе e-learning
security:
  - BearerAuth: []
  - OAuth2: []
servers:
  - url: /api/v1
  - url: https://{Host}/{EnvironmentPrefix}{MicroserviceName}/api/v1
    variables:
        Host:
          default: host.ru
          description: Host на котором развернут микросервис
        EnvironmentPrefix:
          default: ''
          description: |
            Префикс конкретного тестового стенда, выделенного под задачу (feature environment).
            Фактически позволяет окончательно идентифицировать host микросервиса, т.к. хостинге мс в кластере они все хостятся на одном dns - условном host.ru
        MicroserviceName:
          default: content-service
          description: |
            Имя под которым микросервис развернут в кластере микросервисов
            Фактически позволяет окончательно идентифицировать host микросервиса при обращениях к нему
tags:
    - name: content operations
      description: Методы работы с учебными материалами
paths:
  /courses/{courseId}/modules/{moduleId}/content-blocks:
    post:
      tags: 
        - content operations
      operationId: CreateContentBlock
      summary: Добавление блока учебного материала к занятию
      description: Метод создает блок учебного материала с привязкой к курсу, модулю и автору
      parameters:
        - $ref: "#/components/parameters/courseId"
        - $ref: "#/components/parameters/moduleId"
      requestBody:
        content:
          multipart/form-data::
            schema:
              $ref: '#/components/schemas/ContentBlockCreateRq'
          application/json::
            schema:
              $ref: '#/components/schemas/ContentBlockCreateRq'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ContentBlockCreateRp'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
      BearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
      OAuth2:
         type: oauth2
         flows:
          password:
            tokenUrl: https://auth.tusvc.bcs.ru/auth/realms/perseus/protocol/openid-connect/token
            scopes: {}
  parameters:  
    courseId:
      name: courseId
      in: path
      description: Уникальный идентификатор курса
      required: true
      schema:
        type: string
        format: uuid
    moduleId:
      name: moduleId
      in: path
      description: Уникальный идентификатор модуля
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    ContentBlockCreateRq:
      description: Схема тела запроса на создание блока учебного материала в модуле
      type: object
      required:
        - userId
        - file
        - title
      properties:
        userId:
          type: string
          format: uuid
          description: UUID пользователя-автора материала
        file:
          type: string
          format: binary
          description: Файл учебного материала (PDF, video, audio, etc.)
        title:
          type: string
          description: Название учебного материала
          example: "Введение в машинное обучение"
        description:
          type: string
          description: Описание учебного материала
          example: "Базовые понятия и принципы машинного обучения"
        tags:
          type: array
          description: Список тегов для материала
          items:
            type: string

    ContentBlockCreateRp:
      type: object
      description: Схема ответа на запрос создания блока учебного материала в модуле
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: "Учебный материал успешно добавлен"
        data:
          type: object
          items:
            $ref: '#/components/schemas/ContentBlock'
          properties:
            contentBlockId:
              type: string
              format: uuid
              description: UUID созданного блока контента
            courseId:
              type: string
              format: uuid
            moduleId:
              type: string
              format: uuid
            authorId:
              type: string
              format: uuid
            title:
              type: string
              example: "Введение в машинное обучение"
            fileUrl:
              type: string
              description: URL для доступа к загруженному файлу
            createdAt:
              type: string
              format: date-time

    ErrorResponse:
      type: object
      description: Обработка ошибок
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "Произошла ошибка при обработке запроса"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "file"
              error:
                type: string
                example: "Файл превышает максимальный размер 100MB"
    ContentBlock:
      type: object
      description: Объект блока учебного материала
      required:
        - contentBlockId
        - courseId
        - moduleId
        - authorId
        - title
      properties:
        contentBlockId:
          type: string
          format: uuid
          description: UUID блока контента
        courseId:
          type: string
          format: uuid
          description: UUID курса
        moduleId:
          type: string
          format: uuid
          description: UUID модуля
        authorId:
          type: string
          format: uuid
          description: UUID автора
        title:
          type: string
          description: Название материала
        description:
          type: string
          description: Описание материала
        tags:
          type: array
          items:
            type: string
          description: Список тегов
        fileUrl:
          type: string
          description: URL файла
        fileSize:
          type: integer
          description: Размер файла в байтах
        mimeType:
          type: string
          description: MIME-тип файла
        createdAt:
          type: string
          format: date-time
          description: Дата создания
        updatedAt:
          type: string
          format: date-time
          description: Дата обновления"