flowchart LR
Client[Web/Mobile]
API[API Gateway]
Auth[Auth]
Catalog[Catalog]
Order[Order]
Payment[Payment]
PaymentDB[(Order-Payment database)]
Msg[Messaging]
Review[Review]
Fraud[Fraud Detection]
Storage[(Object Storage)]
Notification[Notifications]


Client <--> API
API --> Auth
API --> Review
API --> Catalog
API --> Order
API --> Payment
API --> Notification
Payment <--> PaymentDB
Catalog <--> Storage
Review <--> Storage
Order --> PaymentDB
Catalog --> Fraud
Msg <--> API