openapi: 3.0.3
info:
  title: API отзывов
  version: "1.0.0"
  description: API для оставления отзывов покупателями о товарах или продавцах.

paths:
  /productReviews:
    post:
      summary: Создать отзыв о товаре
      description: Позволяет покупателю оставить отзыв о товаре, включая оценку и текст.
      tags:
        - Отзывы
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - product_id
                - order_id
                - rating
                - text
              properties:
                user_id:
                  type: string
                  format: uuid
                  example: f3009026-ae79-461e-a2ea-d701c13b6088
                product_id:
                  type: string
                  format: uuid
                  description: ID товара (или продавца)
                  example: a94d7e02-7350-4a6b-97a0-5b96d94555a7
                order_id:
                  type: string
                  format: uuid
                  description: ID заказа, подтверждающего покупку
                  example: d4cefb25-05c5-44ff-a591-3a9812864b5d
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  example: 4
                text:
                  type: string
                  maxLength: 2000
                  example: "очень качественный товар, доставили вовремя!!"
      responses:
        "201":
          description: Отзыв успешно опубликован
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: "отзыв успешно опубликован"
                  rating:
                    type: integer
                    example: 4
                  text:
                    type: string
                    example: "очень качественный товар, доставили вовремя!!"
        "400":
          description: Некорректные данные запроса (например, рейтинг вне диапазона)
        "401":
          description: Пользователь не авторизован
        "404":
          description: Товар или заказ не найден
