graph LR
    CLIENT[Клиенты] --> CDN[CDN]
    CDN --> LB[Load Balancer]
    LB --> K8S[Kubernetes Cluster]
    
    subgraph K8S [Продукционный кластер]
        API[API Gateway]
        AUTH[Auth Service]
        PROD[Product Service]
        TRIP[Trip service]
    end
    
    K8S --> DB[(Основная БД)]
    K8S --> CACHE[(Кэш Redis)]
    K8S --> MQ[Message Queue]