graph TD
    WEB[Web Client] --> API[API Gateway]
    MOB[Mobile App] --> API
    API --> USER[User Service]
    API --> Trip[Trip Service]
    API --> PAYMENT[Payment Service]
    API --> NOTIFY[Notification Service]
    API --> SCOOT[Scooter Service] 
    API --> loT[loT Message Broker]
    API --> GEO[Geofencing Service]
    API --> PAYMENT[Payment Service]



  